// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(SurfsUpDbContext))]
    [Migration("20211120165917_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Database.Model.BafuSurfSpot", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("BafuSurfSpots");
                });

            modelBuilder.Entity("Database.Model.MswSurfSpot", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("MswSurfSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
