// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(SurfsUpDbContext))]
    partial class SurfsUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Database.Model.SurfSpot", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("SurfSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
